version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app:cached
      - /app/node_modules
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
    command: npm run dev 